import { UserSeedInput } from '../../types/user.types';

export const userDevData: UserSeedInput[] = [
  {
    username: 'leila.ahmadi',
    password: 'LeilaPass2024!',
    email: 'leila.ahmadi@eventhorizon.com',
    name: 'Leila Ahmadi',
    role: 'admin',
  },
  {
    username: 'samuel.okoro',
    password: 'SamuelSecure#1',
    email: 'samuel.okoro@eventhorizon.com',
    name: 'Samuel Okoro',
    role: 'staff',
  },
  {
    username: 'mingyu_zhang',
    password: 'MingyuZhang!88',
    email: 'mingyu.zhang@eventhorizon.com',
    name: 'Mingyu Zhang',
    role: 'staff',
  },
  {
    username: 'ines.garcia',
    password: 'GarciaInes2025!',
    email: 'ines.garcia@example.com',
    name: 'Inés García',
    role: 'user',
  },
  {
    username: 'lucas_silva',
    password: 'LucasSilva@321',
    email: 'lucas.silva@example.com',
    name: 'Lucas Silva',
    role: 'user',
  },
  {
    username: 'aanya_kapoor',
    password: 'AanyaK2024*',
    email: 'aanya.kapoor@example.com',
    name: 'Aanya Kapoor',
    role: 'user',
  },
  {
    username: 'noah-martin',
    password: 'NoahM!pass',
    email: 'noah.martin@test.com',
    name: 'Noah Martin',
    role: 'user',
  },
  {
    username: 'alexis.tan',
    password: 'AlexisT!2025',
    email: 'alexis.tan@example.com',
    name: 'Alexis Tan',
    role: 'user',
  },
  {
    username: 'jamal_ali',
    password: 'AliSecurePass!',
    email: 'jamal.ali@example.com',
    name: 'Jamal Ali',
    role: 'user',
  },
  {
    username: 'sofia.giannopoulos',
    password: 'SofiaGian#2025',
    email: 'sofia.giannopoulos@example.com',
    name: 'Sofia Giannopoulos',
    role: 'user',
  },
  {
    username: 'morgan.lee',
    password: 'MorganLee2025',
    email: 'morgan.lee@example.com',
    name: 'Morgan Lee',
    role: 'user',
  },
];