name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: event_horizon_test
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Set up test environment
        run: |
          echo "PGUSER=postgres" > .env.test
          echo "PGPASSWORD=postgres" >> .env.test
          echo "PGDATABASE=event_horizon_test" >> .env.test
          echo "PGHOST=localhost" >> .env.test
          echo "PGPORT=5432" >> .env.test
          echo "NODE_ENV=test" >> .env.test

      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Run tests
        env:
          NODE_ENV: test
          PGDATABASE: event_horizon_test
          PGUSER: postgres
          PGPASSWORD: postgres
          PGHOST: localhost
          PGPORT: 5432
        run: npm test
